# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

<class 'Exception'>: File `'initialise.py'` not found.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.__version__
np.version.version

'1.21.6'

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
arr = np.zeros((10,10))
print("%d bytes" % (arr.size * arr.itemsize))

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
%run python -c "import numpy; numpy.info(numpy.add)"

ERROR:root:File `'python.py'` not found.


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
arr = np.arange(10, 50)
print(arr[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
arr = np.arange(9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [13]:
arr = [1, 2, 0, 0, 4, 0]

for i, elem in enumerate(arr):
    if elem != 0:
        print(i)

#Another version        
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

0
1
4
(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [14]:
print(np.eye(3, 3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [15]:
print(np.eye(3, 3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [16]:
print(np.random.random((3, 3, 3)))

[[[0.44283246 0.57807585 0.78932167]
  [0.80496297 0.29425217 0.99474088]
  [0.97536704 0.18618412 0.18500002]]

 [[0.63701992 0.27111652 0.67124874]
  [0.09261169 0.22636733 0.29502398]
  [0.16170636 0.41554107 0.82045892]]

 [[0.56507854 0.83742686 0.06976537]
  [0.10190825 0.25084166 0.60919332]
  [0.18241356 0.26127314 0.01709852]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [17]:
arr = np.random.random((10, 10))
print(arr.min())
print(arr.max())

0.011802793524335775
0.9565771856057219


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [18]:
arr = np.random.random(30)
print(arr.mean())

0.49698540872613256


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [19]:
arr = np.ones((10, 10))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [20]:
arr = np.ones((10, 10))
arr = np.pad(arr, pad_width = 1, mode = 'constant', constant_values = 0)
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [21]:
arr = np.ones((10, 10))

arr[:, [0, -1]] = 0
arr[[0, -1], :] = 0
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [24]:
print(0 * np.nan) #nan ++
print(np.nan == np.nan) #true --
print(np.inf > np.nan) #false ++
print(np.nan - np.nan) #nan ++
print(np.nan in set([np.nan])) #nan --
print(0.3 == 3 * 0.1) #false ++

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [25]:
arr = np.zeros((5, 5))
for i in range(len(arr)):
    for j in range(len(arr)):
        if i == j:
            arr[i][j - 1] = i
print(arr)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [26]:
Z = np.diag(1 + np.arange(4), k = -1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [27]:
arr = np.zeros((8, 8), dtype = int)

arr[1::2, ::2] = 1
arr[::2, 1::2] = 1

print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [28]:
print(np.unravel_index(99, (6, 7, 8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
print(np.tile([[0, 1], [1, 0]], (4, 4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [29]:
arr = np.random.random((5, 5))

arr = (arr - np.mean(arr)) / (np.std(arr))
print(arr)

[[-1.69106494  1.00837699  1.29783595 -0.91403436  1.52507931]
 [-0.57719979  0.85194398 -0.3050502  -1.74121452 -0.42896256]
 [-0.17314427  1.47070039  0.03823623 -0.9765382  -0.61480713]
 [ 0.9615791   0.84033507  0.77773574 -1.5312708   0.43217612]
 [ 0.04525018 -0.621375   -1.08531066 -0.02111434  1.4318377 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [30]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
z = np.dot(np.ones((5, 3)), np.ones((3, 2)))
print(z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
z = np.arange(11)

for i in range(len(z)):
    if (z[i] > 3) and (z[i] < 8):
        z[i] = - z[i]

print(z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [ ]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [8]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-8-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-8-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [47]:
arr = np.random.normal(-100, +100, 10)
print(arr)
print(np.copysign(np.ceil(np.abs(arr)), arr))

[ -58.33933629   66.63248255 -210.56051381 -269.80337283 -163.42348026
 -205.48523552 -174.9993034  -229.98043933 -219.08114988 -130.39397675]
[ -59.   67. -211. -270. -164. -206. -175. -230. -220. -131.]


#### 30. How to find common values between two arrays? (★☆☆)

In [9]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([0, 2, 7, 8, 9, 101])

print(np.intersect1d(arr1, arr2))

[2]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [16]:
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [11]:
#False
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-11-bfa89e8eb074>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [40]:
from datetime import date, timedelta

today = date.today()
print("Today's date:", today)

yesterday = date.today() - timedelta(days = 1)
print("Yesterday's date:", yesterday)

tomorrow = date.today() + timedelta(days = 1)
print("Tomorrow's date:", tomorrow)

Today's date: 2023-01-15
Yesterday's date: 2023-01-14
Tomorrow's date: 2023-01-16


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [43]:
july = np.arange('2016-07', '2016-08', dtype='datetime64[D]')

for elem in enumerate(july):  
  print(elem[1])

2016-07-01
2016-07-02
2016-07-03
2016-07-04
2016-07-05
2016-07-06
2016-07-07
2016-07-08
2016-07-09
2016-07-10
2016-07-11
2016-07-12
2016-07-13
2016-07-14
2016-07-15
2016-07-16
2016-07-17
2016-07-18
2016-07-19
2016-07-20
2016-07-21
2016-07-22
2016-07-23
2016-07-24
2016-07-25
2016-07-26
2016-07-27
2016-07-28
2016-07-29
2016-07-30
2016-07-31


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [44]:
A = np.ones(3) * 1
B = np.ones(3) * 2
np.add(A, B, out = B)
np.divide(A, 2, out = A)
np.negative(A, out = A)
np.multiply(A, B, out = A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [52]:
arr = np.random.normal(0, 100, 10)

print(arr)
print(arr.astype(int))
print(np.copysign(np.ceil(np.abs(arr)) - 1, arr))
print(arr // 1)
print(np.floor(arr))

[  8.66742318 -41.83919878  49.18258514  11.60465206 -34.14572906
  48.02270464  -1.54340675 -58.56093041 100.75151923 -71.03038496]
[  8 -41  49  11 -34  48  -1 -58 100 -71]
[  8. -41.  49.  11. -34.  48.  -1. -58. 100. -71.]
[  8. -42.  49.  11. -35.  48.  -2. -59. 100. -72.]
[  8. -42.  49.  11. -35.  48.  -2. -59. 100. -72.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [4]:
import numpy as np

arr = np.zeros((5, 5))
arr += np.arange(5)

print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [173]:
def generate(n):
    for i in range(n):
        yield i

n = 10

arr = np.fromiter(generate(n), dtype = int, count=-1)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [54]:
lst = np.linspace(0, 1, 10 + 1)
print(lst)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [13]:
lst = np.random.random(10)
lst.sort()
print(lst)

[0.15539105 0.21118388 0.27464961 0.61000557 0.67540029 0.69001982
 0.73822692 0.74107463 0.8993322  0.94617269]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [55]:
arr = np.arange(10)
np.add.reduce(arr)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [66]:
A = np.random.random(10).astype(int)
B = np.random.random(10).astype(int)

if len(A) == len(B):
  print('Equal')
else:
  print('Not equal')

Equal


#### 43. Make an array immutable (read-only) (★★☆)

In [68]:
arr = np.zeros(10)
arr.flags.writeable = False
print("Test the array is read-only or not:")
print("Try to change the value of the first element:")
arr[0] = 1

Test the array is read-only or not:
Try to change the value of the first element:


ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [77]:
z = np.random.random((10,2))
x, y = z[:, 0], z[:, 1]
r = np.sqrt(x ** 2 + y ** 2)
t = np.arctan2(y, x)
print(r)
print(t)

[0.82399518 1.11621575 0.77612583 0.15542574 0.27171168 0.66493085
 0.90548552 1.2017613  0.98321596 0.43401551]
[0.67034855 1.09867148 0.7157879  0.11977907 0.42481461 1.51130568
 1.42828032 0.91200389 0.97281992 0.20493142]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [74]:
arr = np.random.random(10)
print(arr)
idx = np.where(arr == max(arr))
arr[idx] = 0
print(arr)

[0.70366868 0.34476634 0.27134214 0.70442744 0.4906524  0.49378196
 0.53392741 0.62893521 0.67638079 0.0868648 ]
[0.70366868 0.34476634 0.27134214 0.         0.4906524  0.49378196
 0.53392741 0.62893521 0.67638079 0.0868648 ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [182]:
n = 5
arr = np.zeros((n, n), [('x', float),('y', float)])
arr['x'], arr['y'] = np.meshgrid(np.linspace(0, 10, n),
                                 np.linspace(0, 10, n))
print(arr)

[[( 0. ,  0. ) ( 2.5,  0. ) ( 5. ,  0. ) ( 7.5,  0. ) (10. ,  0. )]
 [( 0. ,  2.5) ( 2.5,  2.5) ( 5. ,  2.5) ( 7.5,  2.5) (10. ,  2.5)]
 [( 0. ,  5. ) ( 2.5,  5. ) ( 5. ,  5. ) ( 7.5,  5. ) (10. ,  5. )]
 [( 0. ,  7.5) ( 2.5,  7.5) ( 5. ,  7.5) ( 7.5,  7.5) (10. ,  7.5)]
 [( 0. , 10. ) ( 2.5, 10. ) ( 5. , 10. ) ( 7.5, 10. ) (10. , 10. )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [81]:
x = np.random.random(10)
y = np.random.random(10)

c = np.zeros((10, 10))

for i, elem in enumerate(x):
  for j, elem in enumerate(y):
    c[i, j] = 1 / (x[i] - y[j])

print(c)

[[-4.18259252e+00 -2.82489753e+00 -5.41716364e+01 -1.70716300e+01
  -2.13214976e+00 -1.06571256e+00 -1.42328942e+00 -1.77558692e+01
  -1.22388436e+00 -4.98232411e+00]
 [ 6.25366102e+00  2.22235286e+01  2.62789539e+00  2.93758414e+00
  -1.42821009e+01 -1.85409452e+00 -3.29375020e+00  2.91823323e+00
  -2.39189725e+00  5.04329791e+00]
 [-6.59167636e+00 -3.75072030e+00  1.45096097e+01  3.47186398e+01
  -2.62033550e+00 -1.17514387e+00 -1.62543981e+00  3.21954591e+01
  -1.37044316e+00 -8.82380002e+00]
 [ 2.57572618e+00  3.65856716e+00  1.64239657e+00  1.75824338e+00
   6.31648158e+00 -3.21529829e+00 -1.32852231e+01  1.75129267e+00
  -5.27024597e+00  2.34402480e+00]
 [ 5.36782731e+00  1.40083223e+01  2.45747685e+00  2.72624744e+00
  -2.29205719e+01 -1.94947716e+00 -3.60728872e+00  2.70957277e+00
  -2.55304345e+00  4.45093820e+00]
 [-5.63721579e+00 -3.42112495e+00  2.31300598e+01  3.20830179e+02
  -2.45509281e+00 -1.14071170e+00 -1.56029569e+00  1.86073415e+02
  -1.32384222e+00 -7.19342095e+00

In [82]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [86]:
print('np.int8:')
print(np.iinfo(np.int8).min, np.iinfo(np.int8).max)

print('np.int32:')
print(np.iinfo(np.int32).min, np.iinfo(np.int32).max)

print('np.int64:')
print(np.iinfo(np.int64).min, np.iinfo(np.int64).max)

print('np.float32:')
print(np.finfo(np.float32).min, np.finfo(np.float32).max)

print('np.float64:')
print(np.finfo(np.float64).min, np.finfo(np.float64).max)

np.int8:
-128 127
np.int32:
-2147483648 2147483647
np.int64:
-9223372036854775808 9223372036854775807
np.float32:
-3.4028235e+38 3.4028235e+38
np.float64:
-1.7976931348623157e+308 1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [15]:
arr = np.random.random(10)
for elem in arr:
  print(elem)


0.5253647192022075
0.6402697787553165
0.255608559684793
0.1729650813725293
0.8133615413521453
0.1645447092188853
0.8541317955783809
0.7412033216927248
0.85917354632727
0.4413965156401791


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [65]:
arr = np.random.random(10)
num = 0.5
nearest = []

for i, elem in enumerate(arr):
  nearest.append(abs(num - elem))

nearest_val = arr[nearest.index(min(nearest))]
print(arr)
print(nearest_val)

[0.54594748 0.2558647  0.72419214 0.75657908 0.9099662  0.07629516
 0.41562491 0.49681075 0.75786149 0.67476416]
0.49681074634830424


In [68]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z)
print(v)
print(Z[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
50.519424443045565
51


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [64]:
arr = np.ones(10,  [('position', [('x', float, 1),
                                  ('y', float, 1)]),
                    ('color',    [('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(arr)

[((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))]


/usr/local/lib/python3.8/dist-packages/numpy/core/numeric.py:204: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = empty(shape, dtype, order)


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [61]:
import scipy
import scipy.spatial

Z = np.random.random((10, 2))
D = scipy.spatial.distance.cdist(Z, Z)
print(D)

[[0.         0.42495699 0.23564294 0.64359508 0.23060623 0.12616792
  0.45818138 0.61239214 0.46458246 0.54347597]
 [0.42495699 0.         0.32607656 0.44310986 0.39035615 0.52971613
  0.06006945 0.32729767 0.22568524 0.14125773]
 [0.23564294 0.32607656 0.         0.41023415 0.39339048 0.36022777
  0.38084342 0.61719154 0.25783226 0.46703865]
 [0.64359508 0.44310986 0.41023415 0.         0.75006917 0.76937864
  0.49300142 0.75399259 0.22481408 0.53189824]
 [0.23060623 0.39035615 0.39339048 0.75006917 0.         0.23494921
  0.39262375 0.44357083 0.53435344 0.45764302]
 [0.12616792 0.52971613 0.36022777 0.76937864 0.23494921 0.
  0.55480562 0.66836169 0.58941789 0.63552297]
 [0.45818138 0.06006945 0.38084342 0.49300142 0.39262375 0.55480562
  0.         0.26882453 0.28106708 0.08841001]
 [0.61239214 0.32729767 0.61719154 0.75399259 0.44357083 0.66836169
  0.26882453 0.         0.54922348 0.22429382]
 [0.46458246 0.22568524 0.25783226 0.22481408 0.53435344 0.58941789
  0.28106708 0.54922

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [60]:
arr_float = np.random.randint(0, 10, (5, 5)).astype(np.float32)
print(arr_float)

arr_int = arr_float.view(np.int32)
arr_int[:] = arr_float
print(arr_int)

[[5. 9. 5. 3. 7.]
 [9. 9. 0. 4. 1.]
 [6. 3. 3. 8. 7.]
 [1. 7. 5. 8. 2.]
 [7. 4. 1. 5. 2.]]
[[5 9 5 3 7]
 [9 9 0 4 1]
 [6 3 3 8 7]
 [1 7 5 8 2]
 [7 4 1 5 2]]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [186]:
from io import StringIO

f = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11 ''')

arr = np.genfromtxt(f, delimiter = ",", dtype = np.int32)
print(arr)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [90]:
arr = np.arange(9).reshape(3, 3)
for i, elem in np.ndenumerate(arr):
    print(i, elem)
for i in np.ndindex(arr.shape):
    print(i, arr[i])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [56]:
X, Y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
D = np.sqrt(X * X + Y * Y)
sigma, mu = 1, 0
G = np.exp(-((D - mu) ** 2 / ( 2 * sigma ** 2)))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [53]:
p_elems = 3
arr = np.zeros((5, 5))
np.put(arr, np.random.choice(range(5 * 5), p_elems), 5)
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 5. 0. 0. 5.]
 [0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [37]:
arr = np.random.randint(0, 10, (3, 10))
print(arr)

Y = arr - arr.mean(axis=1, keepdims=True)
print(Y)

[[7 9 4 7 6 4 1 0 2 9]
 [7 8 8 0 8 0 0 8 2 4]
 [1 0 5 0 7 8 5 1 9 0]]
[[ 2.1  4.1 -0.9  2.1  1.1 -0.9 -3.9 -4.9 -2.9  4.1]
 [ 2.5  3.5  3.5 -4.5  3.5 -4.5 -4.5  3.5 -2.5 -0.5]
 [-2.6 -3.6  1.4 -3.6  3.4  4.4  1.4 -2.6  5.4 -3.6]]


#### 59. How to sort an array by the nth column? (★★☆)

In [41]:
arr = np.random.randint(0, 10, (5, 5))
print(arr)
print(arr[arr[:, 1].argsort()])

[[0 8 7 3 4]
 [7 1 4 1 6]
 [5 1 4 8 8]
 [7 7 9 3 3]
 [3 9 5 4 3]]
[[7 1 4 1 6]
 [5 1 4 8 8]
 [7 7 9 3 3]
 [0 8 7 3 4]
 [3 9 5 4 3]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [46]:
arr = np.random.randint(0, 10, (5, 5))
print(arr)

counter = 0

for i in range(len(arr)):
  for j in range(len(arr[i])):
    if arr[i, j] == 0:
      print('Null element')
      print('Row: ', i)
      print('Column: ', j)
      counter += 1
if counter == 0:
  print('No null elements')

[[2 4 8 8 2]
 [3 2 3 1 3]
 [4 8 8 1 4]
 [8 8 2 9 1]
 [4 7 2 5 1]]
No null elements


In [49]:
# null : 0 
Z = np.random.randint(0,3,(3,10))
print(Z)
print((~Z.any(axis=0)).any())

# null : np.nan
Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(Z)
print(np.isnan(Z).all(axis=0))

[[0 2 0 0 1 1 2 0 2 1]
 [2 1 0 2 2 0 1 0 0 2]
 [0 0 2 1 2 1 1 0 2 2]]
True
[[ 0.  1. nan]
 [ 1.  2. nan]
 [ 4.  5. nan]]
[False False  True]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [12]:
arr = np.random.random(10)
num = 0.5
nearest = []

for i, elem in enumerate(arr):
  nearest.append(abs(num - elem))

nearest_val = arr[nearest.index(min(nearest))]
print(arr)
print(nearest_val)

[0.99570976 0.3546234  0.60863817 0.92801004 0.40211675 0.96415239
 0.83550853 0.05636999 0.31176494 0.59980613]
0.4021167524604351


In [15]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(Z)
print(m)

[0.08531948 0.02032124 0.04394156 0.93192978 0.72575242 0.47834625
 0.93206785 0.52943344 0.56138369 0.96479404]
0.47834624936862524


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [22]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [20]:
class Array:
  def __init__(self, arr, name):
      self.arr = arr
      self.name = name

  def printing(self):
      print(self.name)
      print(self.arr)

arr = Array(np.arange(10), "Array size is 10")
arr.printing()

Array size is 10
[0 1 2 3 4 5 6 7 8 9]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [190]:
arr = np.ones(5)
print(arr)
idx = np.random.randint(0, len(arr), 10)
print(idx)
arr += np.bincount(idx, minlength=len(arr))
print(arr)

[1. 1. 1. 1. 1.]
[4 2 3 2 3 4 1 1 3 3]
[1. 3. 3. 5. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [191]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [197]:
w, h = 256, 256
idx = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(idx.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [215]:
arr = np.random.randint(0, 10, (3, 4, 3, 4))
print(arr)

for i in range(3):
  for j in range(4):
    sum = np.sum(arr[i, j])
    print(sum)

[[[[9 6 5 2]
   [9 7 5 1]
   [3 1 8 6]]

  [[5 1 2 7]
   [0 7 1 2]
   [7 5 0 9]]

  [[6 6 2 6]
   [9 2 8 2]
   [3 6 8 9]]

  [[9 2 8 7]
   [7 3 5 9]
   [1 0 7 3]]]


 [[[0 9 5 1]
   [7 9 3 3]
   [7 0 4 6]]

  [[0 3 8 3]
   [1 7 2 5]
   [9 6 8 1]]

  [[2 5 4 5]
   [0 6 9 8]
   [5 0 3 9]]

  [[6 6 7 4]
   [1 6 5 0]
   [1 8 2 9]]]


 [[[7 7 9 5]
   [7 9 2 7]
   [2 5 3 4]]

  [[6 4 1 2]
   [9 9 4 5]
   [3 5 8 9]]

  [[2 9 9 0]
   [9 7 4 2]
   [8 3 2 6]]

  [[8 4 1 6]
   [5 0 0 3]
   [4 9 3 3]]]]
62
46
67
61
54
53
56
55
67
65
61
46


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [243]:
import pandas as pd

D = np.random.uniform(0, 1, 100)
S = np.random.randint(0, 10, 100)

print(pd.Series(D).groupby(S).mean())

0    0.605863
1    0.410571
2    0.507454
3    0.570732
4    0.582303
5    0.427760
6    0.410593
7    0.341340
8    0.482951
9    0.581752
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [216]:
arr1 = np.random.randint(0, 2,(5, 5))
print(arr1)
arr2 = np.random.randint(0, 2,(5, 5))
print(arr2)

print(np.diag(np.dot(arr1, arr2)))

[[0 1 1 0 1]
 [1 0 1 1 1]
 [1 1 1 0 1]
 [0 0 0 1 0]
 [1 1 0 0 0]]
[[0 0 0 0 1]
 [1 0 1 1 1]
 [0 1 0 1 0]
 [1 1 0 1 1]
 [0 1 1 1 0]]
[1 3 2 1 2]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [238]:
arr = np.arange(1, 5 + 1)
print(arr)

zero = np.zeros(3)
print(zero)

for i in range(1, len(arr) * len(zero), 4):
  arr = np.insert(arr, i, zero)

print(arr)

[1 2 3 4 5]
[0. 0. 0.]
[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [240]:
arr1 = np.random.randint(0, 5, (5, 5, 3))
arr2 = np.random.randint(0, 5, (5, 5))
print(arr1 * arr2[:, :, None])

[[[ 0  0  0]
  [ 9  3 12]
  [12 12  0]
  [ 0  0  0]
  [ 6  0  0]]

 [[ 0  0  0]
  [ 1  1  1]
  [ 0  0  0]
  [12  9  6]
  [ 3  4  0]]

 [[ 0  0  0]
  [ 9 12 12]
  [ 4  0  4]
  [ 9 12 12]
  [ 9  0  0]]

 [[ 0  0  0]
  [ 1  3  2]
  [ 4  3  2]
  [ 2  2  8]
  [12 12 16]]

 [[ 2  4  8]
  [ 2  2  8]
  [ 0  0  8]
  [ 0  2  1]
  [ 0  0  0]]]


#### 72. How to swap two rows of an array? (★★★)

In [72]:
arr = np.random.randint(0, 10, (3, 10))
print(arr)

arr[[0, -1]] = arr[[-1, 0]]
print(arr)

[[5 1 3 9 9 6 7 2 1 2]
 [1 3 6 3 5 7 6 9 4 3]
 [3 9 0 7 9 2 1 5 2 9]]
[[3 9 0 7 9 2 1 5 2 9]
 [1 3 6 3 5 7 6 9 4 3]
 [5 1 3 9 9 6 7 2 1 2]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [74]:
faces = np.random.randint(0, 100, (10, 3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0,  1) ( 0, 60) ( 1, 60) ( 5, 62) ( 5, 81) (11, 20) (11, 91) (14, 29)
 (14, 56) (14, 59) (14, 97) (15, 39) (15, 79) (15, 81) (15, 92) (18, 40)
 (18, 88) (20, 91) (23, 26) (23, 70) (26, 70) (29, 59) (39, 79) (40, 88)
 (47, 75) (47, 95) (56, 97) (62, 81) (75, 95) (81, 92)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [75]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [81]:
from numpy.lib.stride_tricks import sliding_window_view

arr = np.arange(20)
print(arr)
print(sliding_window_view(arr, window_shape=3).mean(axis=-1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [80]:
arr = np.arange(20)
print(arr)
print(sliding_window_view(arr, window_shape = 3))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2]
 [ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]
 [11 12 13]
 [12 13 14]
 [13 14 15]
 [14 15 16]
 [15 16 17]
 [16 17 18]
 [17 18 19]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [87]:
arr = np.random.randint(0, 2, 10)
print(arr)
print(np.logical_not(arr, out = arr))

[0 1 0 1 1 1 0 0 0 0]
[1 0 1 0 0 0 1 1 1 1]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [247]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T ** 2).sum(axis=1)
    U = -((P0[:, 0] - p[..., 0]) * T[:, 0] + (P0[:, 1] - p[..., 1]) * T[:, 1]) / L
    U = U.reshape(len(U), 1)
    D = P0 + U * T - p
    return np.sqrt((D ** 2).sum(axis=1))
 
P0 = np.random.randint(-5, 5, (10, 2))
print(P0)
P1 = np.random.randint(-5, 5, (10, 2))
print(P1)
p  = np.random.randint(-5, 5, (1, 2))
print(p)
print(distance(P0, P1, p))

[[ 0 -1]
 [-4  1]
 [ 0 -5]
 [ 4 -2]
 [ 4 -5]
 [ 2  3]
 [ 1  1]
 [-3 -5]
 [-2  4]
 [-4 -1]]
[[ 1  3]
 [ 3  1]
 [ 3 -5]
 [-5  4]
 [ 2 -4]
 [ 3  1]
 [ 3 -3]
 [ 4 -5]
 [ 0  1]
 [ 3  0]]
[[ 0 -5]]
[0.9701425  6.         0.         4.71495167 1.78885438 5.36656315
 3.57770876 0.         3.32820118 4.5254834 ]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [249]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T ** 2).sum(axis=1)
    U = -((P0[:, 0] - p[..., 0]) * T[:, 0] + (P0[:, 1] - p[..., 1]) * T[:, 1]) / L
    U = U.reshape(len(U), 1)
    D = P0 + U * T - p
    return np.sqrt((D ** 2).sum(axis=1))
 
P0 = np.random.randint(-5, 5, (10, 2))
print(P0)
P1 = np.random.randint(-5, 5, (10, 2))
print(P1)
p  = np.random.randint(-5, 5, (1, 2))
print(p)
print(np.array([distance(P0, P1, i) for i in p]))

[[ 0  1]
 [-1  4]
 [-3  0]
 [ 3  0]
 [ 2  2]
 [ 4 -2]
 [ 3 -5]
 [-3  1]
 [ 1 -3]
 [ 3  4]]
[[-4  2]
 [ 0 -2]
 [-2  4]
 [ 1 -2]
 [-4  3]
 [-1 -1]
 [-1 -4]
 [ 4  0]
 [-2 -5]
 [-5 -2]]
[[ 0 -2]]
[[2.9104275  0.         3.39549875 0.70710678 4.27437367 0.78446454
  2.18282063 2.54558441 1.38675049 3.        ]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [250]:
# ???

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[1 0 4 7 4 9 1 5 6 0]
 [5 7 3 0 5 6 2 5 5 0]
 [7 5 8 3 0 2 3 2 8 2]
 [4 9 0 5 3 6 9 2 5 4]
 [7 6 4 6 7 2 3 4 3 8]
 [5 2 8 5 8 9 4 0 3 8]
 [9 7 5 4 4 9 3 9 1 7]
 [4 9 8 5 9 8 1 2 6 6]
 [4 3 4 6 9 7 5 2 1 8]
 [3 1 7 0 8 7 2 9 8 5]]
[[0 0 0 0 0]
 [0 1 0 4 7]
 [0 5 7 3 0]
 [0 7 5 8 3]
 [0 4 9 0 5]]


<ipython-input-250-f2b5781f38bf>:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [125]:
Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
R = []
for i, elem in enumerate(Z):
    r = Z[i:(i + 4)]
    if len(r) == 4:
        R.append(r)
        print(R[i])

[1, 2, 3, 4]
[2, 3, 4, 5]
[3, 4, 5, 6]
[4, 5, 6, 7]
[5, 6, 7, 8]
[6, 7, 8, 9]
[7, 8, 9, 10]
[8, 9, 10, 11]
[9, 10, 11, 12]
[10, 11, 12, 13]
[11, 12, 13, 14]


#### 82. Compute a matrix rank (★★★)

In [122]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [95]:
arr = np.random.randint(0, 10, 100)
print(np.bincount(arr).argmax())

9


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [148]:
arr = np.random.randint(0, 5, (10, 10))
print("Original array:")
print(arr)
n = 3
i = 1 + (arr.shape[0] - n)
j = 1 + (arr.shape[1] - n)
result = np.lib.stride_tricks.as_strided(arr, 
                                         shape=(i, j, n, n), 
                                         strides = arr.strides + arr.strides)
print("\nContiguous 3x3 blocks:")
print(result)

Original array:
[[2 3 0 0 1 0 4 0 4 3]
 [0 0 1 3 0 4 1 4 4 0]
 [1 0 2 3 3 0 3 2 3 3]
 [1 4 3 1 4 4 4 1 0 4]
 [3 1 0 0 3 3 0 2 4 0]
 [3 2 3 4 2 2 1 0 1 0]
 [0 3 0 1 3 4 1 1 4 3]
 [2 2 0 0 3 2 2 0 4 4]
 [3 2 1 2 1 1 1 2 3 2]
 [1 1 1 2 1 4 3 1 2 2]]

Contiguous 3x3 blocks:
[[[[2 3 0]
   [0 0 1]
   [1 0 2]]

  [[3 0 0]
   [0 1 3]
   [0 2 3]]

  [[0 0 1]
   [1 3 0]
   [2 3 3]]

  [[0 1 0]
   [3 0 4]
   [3 3 0]]

  [[1 0 4]
   [0 4 1]
   [3 0 3]]

  [[0 4 0]
   [4 1 4]
   [0 3 2]]

  [[4 0 4]
   [1 4 4]
   [3 2 3]]

  [[0 4 3]
   [4 4 0]
   [2 3 3]]]


 [[[0 0 1]
   [1 0 2]
   [1 4 3]]

  [[0 1 3]
   [0 2 3]
   [4 3 1]]

  [[1 3 0]
   [2 3 3]
   [3 1 4]]

  [[3 0 4]
   [3 3 0]
   [1 4 4]]

  [[0 4 1]
   [3 0 3]
   [4 4 4]]

  [[4 1 4]
   [0 3 2]
   [4 4 1]]

  [[1 4 4]
   [3 2 3]
   [4 1 0]]

  [[4 4 0]
   [2 3 3]
   [1 0 4]]]


 [[[1 0 2]
   [1 4 3]
   [3 1 0]]

  [[0 2 3]
   [4 3 1]
   [1 0 0]]

  [[2 3 3]
   [3 1 4]
   [0 0 3]]

  [[3 3 0]
   [1 4 4]
   [0 3 3]]

  [[3 0 3]
   [4 4 4]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [149]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2, 3] = 42
print(S)

[[ 1 14  6 17 12]
 [14  9  6  3  6]
 [ 6  6  8 42 12]
 [17  3 42  3  4]
 [12  6 12  4  6]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [154]:
p, n = 3, 5
arr = np.ones((p, n, n))
arr_vec = np.ones((p, n, 1))
print(arr)
print(arr_vec)

sum = np.tensordot(arr, arr_vec, axes=[[0, 2], [0, 1]])
print(sum)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[[[1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]]]
[[15.]
 [15.]
 [15.]
 [15.]
 [15.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [2]:
import numpy as np
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [6]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [7]:
arr = np.arange(10000)
arr.sort()

n = 10
print(arr[-n:])

[9990 9991 9992 9993 9994 9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [254]:
import itertools

somelists = [[1, 2, 3], 
             [4, 5], 
             [6, 7]]

for element in itertools.product(*somelists):
    print(element)

(1, 4, 6)
(1, 4, 7)
(1, 5, 6)
(1, 5, 7)
(2, 4, 6)
(2, 4, 7)
(2, 5, 6)
(2, 5, 7)
(3, 4, 6)
(3, 4, 7)
(3, 5, 6)
(3, 5, 7)


In [251]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [144]:
arr = np.array([("Hello", 2.5, 3),
                ("World", 3.6, 2)])
arr_record = np.core.records.fromarrays(arr.T, 
                                        names='col1, col2, col3', 
                                        formats = 'S8, f8, i8')
print(arr_record)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [142]:
arr = np.random.randint(0, 10, 10)
print(arr)

print([elem ** 3 for i, elem in enumerate(arr)])
print(np.einsum('i,i,i->i', arr, arr, arr))
print(arr * arr * arr)

[9 7 6 3 7 4 3 9 0 8]
[729, 343, 216, 27, 343, 64, 27, 729, 0, 512]
[729 343 216  27 343  64  27 729   0 512]
[729 343 216  27 343  64  27 729   0 512]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [135]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
print(A)
print(B)

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[[0 4 4]
 [1 0 0]
 [0 2 4]
 [2 0 1]
 [1 3 1]
 [2 3 4]
 [0 1 3]
 [0 2 1]]
[[2 0]
 [0 2]]
[0 1 2 3 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [133]:
from traceback import print_stack
arr = np.random.randint(0, 10, (10, 3))

for i in range(1, 5):
  arr[np.random.randint(0, len(arr) - 1)] = np.array([5 for i in range(len(arr[i]))])
print(arr)

idx = []
for i in range(len(arr)):
  counter = 0
  for j in range(1, len(arr[i])):
    if arr[i, j] == arr[i, j - 1]:
      counter += 1
  if counter == 2:
    idx.append(i)
arr_unequal = np.delete(arr, idx, 0)
print(arr_unequal)

[[2 6 6]
 [5 6 9]
 [5 5 5]
 [4 7 3]
 [6 2 3]
 [5 5 5]
 [5 5 5]
 [5 5 5]
 [2 7 1]
 [9 9 9]]
[[2 6 6]
 [5 6 9]
 [4 7 3]
 [6 2 3]
 [2 7 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [99]:
arr = np.array([2 ** i for i in range(0, 8)], dtype=np.uint8)
print(arr)

print(np.unpackbits(arr[:, np.newaxis], axis=1))

[  1   2   4   8  16  32  64 128]
[[0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [114]:
arr = np.random.randint(0, 10, (5, 5))
arr[-1] = arr[0]
print(arr)

arr_unique = np.unique(arr, axis=0)
print(arr_unique)

[[1 5 1 1 8]
 [9 7 3 0 3]
 [6 2 0 3 1]
 [1 2 9 9 9]
 [1 5 1 1 8]]
[[1 2 9 9 9]
 [1 5 1 1 8]
 [6 2 0 3 1]
 [9 7 3 0 3]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [118]:
A = np.random.randint(0, 10, 10)
print(A)

B = np.random.randint(0, 10, 10)
print(B)

print('np.sum(A): ', np.einsum('i->', A))
print('A * B: ', np.einsum('i,i->i', A, B))
print('np.inner(A, B): ', np.einsum('i,i', A, B))    
print('np.outer(A, B): \n', np.einsum('i,j->ij', A, B))

[6 9 7 3 9 8 9 1 8 0]
[5 2 8 0 7 5 9 0 1 5]
np.sum(A):  60
A * B:  [30 18 56  0 63 40 81  0  8  0]
np.inner(A, B):  296
np.outer(A, B): 
 [[30 12 48  0 42 30 54  0  6 30]
 [45 18 72  0 63 45 81  0  9 45]
 [35 14 56  0 49 35 63  0  7 35]
 [15  6 24  0 21 15 27  0  3 15]
 [45 18 72  0 63 45 81  0  9 45]
 [40 16 64  0 56 40 72  0  8 40]
 [45 18 72  0 63 45 81  0  9 45]
 [ 5  2  8  0  7  5  9  0  1  5]
 [40 16 64  0 56 40 72  0  8 40]
 [ 0  0  0  0  0  0  0  0  0  0]]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [255]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [162]:
arr = np.random.randint(0, 5, (3, 5))
print(arr)

n = 10

for i in range(len(arr)):
  n_sum = np.sum(arr[i])
  if n_sum == n:
    print(arr[i])

[[3 3 1 1 0]
 [2 1 4 2 1]
 [3 1 3 1 4]]
[2 1 4 2 1]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [1]:
import numpy as np

X = np.random.randn(100) # random 1D array
print(X)
N = 10000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
print(idx)

[-1.29163722  1.10884191  0.42793435 -1.69500143  1.24627594  0.58359445
  0.84859828 -0.28387923  1.69991418 -1.19912761  0.41128406 -1.6895508
 -0.28956932  2.08431105 -0.92941934 -2.36478462 -0.39485683  1.30876918
 -0.46412247  0.87012115 -0.82974434 -2.96821063  0.27057689 -1.5371998
 -0.56200097 -0.12993548  0.08636859 -0.28713575 -1.27113624  1.0009459
 -0.24134734  0.13388486  0.86205476  0.72967366 -0.17611177  0.31451042
  1.39930946 -0.15296254  0.6048383   0.09755714 -0.1816061   0.27929843
  0.1103684  -0.56997156 -2.01345192 -0.02509557  0.0634593  -2.5803307
  0.31881781  1.92794411  0.34470994  0.53723838  2.4743292  -0.19436156
  1.57868351  0.81698369  0.24164205 -0.43714807 -0.29567232  0.07626772
 -0.23527716  0.02279043  0.05337526  0.39283699 -1.00132289 -0.61105833
 -1.19134266  2.19766945  0.48714609  0.3243458  -0.04647933  0.53636913
  1.57034172 -1.06504504 -0.55887257  0.40757584  0.24956395  1.04575118
  0.36846175  1.61473494 -1.15254629  0.68531585 -0.039

In [2]:
means = X[idx].mean(axis=1)
print(means)


[-0.22483428 -0.02797209 -0.02099834 ...  0.02920668 -0.08327588
 -0.0670003 ]


In [6]:
per = np.percentile(means, [5, 95])
print(per)

[-0.13934873  0.20746307]
